w8d1/RedditClone/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resource :session, only: [:create, :new, :destroy]
  resources :users
  resources :subs, except: [:destroy]
  resources :posts, except: [:index]
end

w8d1/RedditClone/app/models/post.rb
class Post < ApplicationRecord
  validates :title, :author_id, presence: true
  #attr_accessor :sub_ids <--- same as def sub_ids=()

  belongs_to :author, 
  foreign_key: :author_id, 
  class_name: :User

  has_many :post_subs,
  foreign_key: :post_id,
  class_name: :PostSub

  has_many :subs,
  through: :post_subs,
  source: :sub

  def sub_ids=(sub_ids)
    @sub_ids = sub_ids
  end
end

w8d1/RedditClone/app/models/post_sub.rb
class PostSub < ApplicationRecord

    belongs_to :post,
        foreign_key: :post_id,
        class_name: :Post

    belongs_to :sub,
        foreign_key: :sub_id,
        class_name: :Sub

    # def sub_id=(id)
    #     self.sub_id = id
    # end
end

w8d1/RedditClone/app/models/sub.rb
class Sub < ApplicationRecord
  validates :title, :description, :moderator_id, presence: true

  belongs_to :moderator, 
  foreign_key: :moderator_id, 
  class_name: :User

  has_many :post_subs,
  foreign_key: :sub_id,
  class_name: :PostSub

  has_many :posts,
  through: :post_subs,
  source: :post
end

w8d1/RedditClone/app/models/user.rb
class User < ApplicationRecord
    attr_reader :password
    validates :username, :session_token, presence: true, uniqueness: true
    validates :password_digest, presence: true
    validates :password, length: { minimum: 6 }, allow_nil: true
    after_initialize :ensure_session_token
    
    has_many :subs, 
    foreign_key: :moderator_id, 
    class_name: :Sub
    
    has_many :posts, 
    foreign_key: :author_id, 
    class_name: :Post
    
    #spire

    def self.find_by_credentials(username, password)
        user = User.find_by(username: username)
        user && user.is_password?(password) ? user : nil
    end

    def password=(password)
        @password = password
        self.password_digest = BCrypt::Password.create(password)
    end

    def is_password?(password)
        BCrypt::Password.new(self.password_digest).is_password?(password)
    end

    def reset_session_token!
        self.session_token = SecureRandom.base64
        self.save!
        self.session_token
    end

    def ensure_session_token
        self.session_token ||= SecureRandom.base64
    end
end

w8d1/RedditClone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?

    def current_user
        @current_user ||= User.find_by(session_token: session[:session_token])
    end

    def require_logged_in
        redirect_to new_session_url unless logged_in?
    end

    def logged_in?
        !!current_user
    end

    def login(user)
        session[:session_token] = user.reset_session_token!
        @current_user = user
    end

    def logout
        current_user.reset_session_token! if logged_in?
        session[:session_token] = nil
    end

    def require_moderator
        sub = Sub.find_by(id: params[:id])
        flash[:errors] = ['You are not the moderator of this sub!']
        redirect_to sub_url(sub) unless current_user.subs.include?(sub)
    end
end

w8d1/RedditClone/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
    render :new
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      params[:post][:sub_ids].each do |sub_id|
        PostSub.create!(post_id: @post.id, sub_id: sub_id)
      end
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def destroy
    @post = current_user.posts.find_by(id: params[:id])
    if @post && @post.destroy
      redirect_to sub_url(@post.sub_id)
    end
  end

  def show
    @post = Post.find_by(id: params[:id])
    render :show
  end

  def edit
    @post = Post.find_by(id: params[:id])
    render :edit
  end

  def update
    @post = current_user.posts.find_by(id: params[:id])
    if @post && @post.update(post_params)
      redirect_to post_url(@post)
    else
      flash.now[:errors] = ['Post must have a title!']
      render :edit
    end
  end

  private
  def post_params
    params.require(:post).permit(:title, :url, :content, :author_id, sub_ids: [])
  end
end

w8d1/RedditClone/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    before_action :require_logged_in, only: [:destroy]

    def new
    end

    def create
        @user = User.find_by_credentials(params[:user][:username],
        params[:user][:password])

        if @user
            login(@user)
            redirect_to subs_url
        else  
            flash.now[:errors] = ['Invalid username or password']
            render :new
        end
    end

    def destroy
        logout
        redirect_to new_session_url
    end
end

w8d1/RedditClone/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :require_moderator, only: [:edit, :update]

  def new
    @sub = Sub.new
    render :new
  end
  
  def create
    @sub = Sub.new(sub_params)

    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def index
    @subs = Sub.all 
    render :index
  end

  def show
    @sub = Sub.find_by(id: params[:id])
    render :show
  end

  def edit
    @sub = Sub.find_by(id: params[:id])
    render :edit
  end

  def update
    @sub = current_user.subs.find_by(id: params[:id])

    if @sub && @sub.update(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = ['You are not the moderator of this sub']
      render :edit
    end
  end

  private
  def sub_params
    params.require(:sub).permit(:title, :description, :moderator_id)
  end
end

w8d1/RedditClone/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_logged_in, except: [:new, :create]

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login(@user)
      redirect_to subs_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def index
    @users = User.all 
    render :index
  end

  def show
    @user = User.find_by(id: params[:id])
    render :show
  end

  def edit
    @user = User.find_by(id: params[:id])
    render :edit
  end

  def update
    @user = User.find_by(id: params[:id])

    if @user.update(user_params)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :edit
    end
  end

  def destroy
    @user = User.find_by(id: params[:id])
    @user.delete
    redirect_to users_url
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

w8d1/RedditClone/app/helpers/posts_helper.rb
module PostsHelper
end

w8d1/RedditClone/app/helpers/subs_helper.rb
module SubsHelper
end

w8d1/RedditClone/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if logged_in? %>
      <form action="<%= session_url %>" method="POST">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <input type="hidden" name="_method" value="DELETE">
        <input type="submit" value="Sign Out">
      </form>
    <% else %>
      <a href="<%= new_session_url %>">Sign In!</a>
      <a href="<%= new_user_url %>">Sign Up!</a>
    <% end %>
  
    <%= yield %>

    <% if flash[:errors] %>
      <p>
        <%= flash[:errors].join(', ') %>
      </p>
    <% end %>
    
  </body>
</html>

w8d1/RedditClone/app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<form action="<%= post_url(@post) %>" method="POST">
    <input type="hidden" name="_method" value="PATCH">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <label>Title:
        <input type="text" name="post[title]" value="<%= @post.title %>">
    </label>

    <br>

    <label>URL:
        <input type="text" name="post[url]" value="<%= @post.url %>">
    </label>

    <br>

    <label>Content:
        <input type="text" name="post[content]" value="<%= @post.content %>">
    </label>

    <p>Subs:</p>
    
    <% Sub.all.each do |sub| %>
        <label>
        <input 
            type="checkbox" 
            name="post[sub_ids][]" 
            value="<%= sub.id %>"
            <%= "checked" if @post.sub_ids.include?(sub.id) %>>
        <%= sub.title %>
        </label>
        <br>
    <% end %>
    
    <br>
    
    <input type="hidden" name="post[author_id]" value="<%= current_user.id %>">

    <input type="submit" value="Update Post">
</form>

w8d1/RedditClone/app/views/posts/new.html.erb
<h1>Create Post</h1>

<form action="<%= posts_url %>" method="POST">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <label>Title:
        <input type="text" name="post[title]" value="<%= @post.title %>">
    </label>

    <br>

    <label>URL:
        <input type="text" name="post[url]" value="<%= @post.url %>">
    </label>

    <br>

    <label>Content:
        <input type="text" name="post[content]" value="<%= @post.content %>">
    </label>

    <p>Subs:</p>
    
    <% Sub.all.each do |sub| %>
        <label>
        <input type="checkbox" name="post[sub_ids][]" value="<%= sub.id %>">
        <%= sub.title %>
        </label>
    <% end %>
    
    
    <input type="hidden" name="post[author_id]" value="<%= current_user.id %>">

    <input type="submit" value="Create Post">
</form>

w8d1/RedditClone/app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<ul>
    <li><%= @post.url %></li>
    <li><%= @post.content %></li>
    <li><%= User.find_by(id: @post.author_id).username %></li>
</ul>

<br>

<a href="<%= edit_post_url(@post) %>">Edit Post</a>

w8d1/RedditClone/app/views/subs/edit.html.erb
<h1>Edit Sub</h1>

<form action="<%= sub_url(@sub) %>" method="POST">
    <input type="hidden" name="_method" value="PATCH">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <label>Title:
        <input type="text" name="sub[title]" value="<%= @sub.title %>">
    </label>

    <br>

    <label>Description:
        <input type="text" name="sub[description]" value="<%= @sub.description %>">
    </label>

    <input type="hidden" name="sub[moderator_id]" value="<%= current_user.id %>">

    <input type="submit" value="Update Sub">

</form>

w8d1/RedditClone/app/views/subs/index.html.erb
<h1>All Subs</h1>

<ul>
<% @subs.each do |sub| %>
    <li>
        <a href="<%= sub_url(sub) %>"><%= sub.title %></a>
    </li>
<% end %>
</ul>

w8d1/RedditClone/app/views/subs/new.html.erb
<h1>Create Sub</h1>

<form action="<%= subs_url %>" method="POST">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <label>Title:
        <input type="text" name="sub[title]" value="<%= @sub.title %>">
    </label>

    <br>

    <label>Description:
        <input type="text" name="sub[description]" value="<%= @sub.description %>">
    </label>

    <input type="hidden" name="sub[moderator_id]" value="<%= current_user.id %>">

    <input type="submit" value="Create Sub">

</form>

w8d1/RedditClone/app/views/subs/show.html.erb
<h1><%= @sub.title %></h1>

<h3>Description</h3>
<p><%= @sub.description %></p>

<h2>Posts</h2>
<ul>
    <% @sub.posts.each do |post| %>
        <li>
            <a href="<%= post_url(post) %>"><%= post.title %></a>
        </li>
    <% end %>
</ul>

<br>

<a href="<%= new_post_url %>">Create a post</a>

<br>

<% if current_user.id == @sub.moderator_id %>

    <a href="<%= edit_sub_url(@sub) %>">Edit Sub</a>

<% end %>

<br>

<a href="<%= subs_url %>">All Subs</a>